### ISSUE TITLE
ios 9.3.3 app not starting up

### ISSUE THREAD

**Issue by krisrok** [MaKleSoft/padlock#108]
i'm not too sure this is the right place for ios-related issues, but here we go:

on ios 9.3.3 the 2.0 version of the app launches with a blue color and then hangs there forever, rendering the app useless (and me fearful of password loss).

**Comment by MaKleSoft** [comment]
v2.0.0 wasn't actually supposed to ship out to iOS 9 users. We were planning to add support for iOS 9 later but due to a bug in out build pipeline the build target was mistakenly set to iOS 9 and the mistake was not noticed until after the new version had been released. We're working on adding iOS 9 support now and will release a patch as soon as possible. Don't worry though, your data should be save. Just sit tight until we release the patch and don't uninstall the app. Sorry for the inconvenience!

**Comment by krisrok** [comment]
ah a silver lining :)

is there a way to save the db and downgrade and restore the db? my device is jailbroken (hence 9.3.3) so all i need is some info and, uhm, an older build's ipa.

**Comment by MaKleSoft** [comment]
All the relevant files for restoring your data should be located in the `/var/mobile/Containers/Data/Application/[app_uuid]/Library/Caches` and `/var/mobile/Containers/Data/Application/[app_uuid]/Library/WebKit/` directories. `[app_uuid]` will be different for each install, so you'll have to figure out the exact location yourself. Once you've downgraded to the older version simply restoring those folders should do the trick (or at least I hope so, I haven't tested it). As for the ipa - if you have a Mac with XCode installed you can actually build it yourself! Instructions can be found here: https://github.com/MaKleSoft/padlock#building-for-mobile

I feel like a warning is in place here... Running a security-sensitive application on a jailbroken device with an outdated OS is, generally speaking, a **very** bad idea. I hope you have a good reason to do it and, more importantly, really know what you're doing.

**Comment by MaKleSoft** [comment]
So it turns out that adding backward compatibility for iOS 9.x would a) be more work than anticipated and b) require some changes that would have a negative impact on performance and stability not only on iOS 9 but other versions as well. Considering this and the fact that the number of iOS 9 users is vanishingly small, we've decided that 2.0 will not support iOS versions older than iOS 10. We've adjusted the build target accordingly and released a new version. You should now be able to downgrade by removing the app and re-downloading it from the app store. @krisrok Let me know if you if you need any more help!

**Comment by krisrok** [comment]
thanks for the effort!

i've already downgraded using a jb-app which lets the user install older version directly from within the app store.
your efforts sure will make it easier for others and myself in the future. 

i see where your security advice is coming from. as a developer myself i just have to take the risk in light of how i customize this device to my needs with a jb. i'll try to stay safe, thanks!

keep up the good work!

**Comment by krisrok** [comment]
thanks for the effort!

i've already downgraded using a jb-app which lets the user install older version directly from within the app store.
your efforts sure will make it easier for others and myself in the future. 

i see where your security advice is coming from. as a developer myself i just have to take the risk in light of how i can customize this device to my needs with a jb. i'll try to stay safe, thanks!

keep up the good work!
