### ISSUE TITLE
Unable to synchronize with padlock cloud

### ISSUE THREAD

**Issue by c00w** [MaKleSoft/padlock#111]
All of my apps appear to be disconnecting and then losing the stored information (Android) or just hanging indefinitely (chromeos) when I try and sign in. This is extremely painful. Please let me know what information you need to debug this. I do get the email for new devices when I reconnect them to the padlock cloud but they fail to sync. My account is paid + up to date according to cloud.padlock.io

**Comment by MaKleSoft** [comment]
@c00w Sorry to hear you're having problems! Your issue with Chrome OS is likely related to a bug in version 2.0.0 that has since been fixed. Reinstalling the app should solve the problem.

As for your problems on Android, I'll need some more information on that. Can you explain in more detail what exactly you are experiencing? Does this only happen on Android? Which version of Android are you using?

**Comment by c00w** [comment]
It is Android 8.0. looks like it has resolved itself so I'll just reinstall
all my chromeos apps tonight.

**Comment by MaKleSoft** [comment]
@c00w Closing this now if you don't mind. If you continue to experience problems feel free to reopen!
