### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by quesada** [MaKleSoft/padlock#114]
Hi, 

Just a quick enquire about the linux version. Apologies if issues are not the best way to contact you, but I couldn't find any other way.

**Comment by MaKleSoft** [comment]
Hi @quesada. Padlock does already run on Linux but we are still figuring out some details regarding distribution (specifically code signing and auto updates) which is why we haven't published any official builds yet. If you can't wait for the official release and are somewhat comfortable with the terminal, you can pretty easily build it from source though! You can find some instructions [here](https://github.com/MaKleSoft/padlock#building-for-desktop). Let me know if you need any help!

**Comment by Auronius** [comment]
I would like to see Padlock available for Linux too. I am interested in running Padlock on Debian and Ubuntu based Linux distributions.

**Comment by MaKleSoft** [comment]
Well, you've been heard! Demand for Linux has certainly been much stronger than anticipated. Gonna make this a priority for the next release.

**Comment by MaKleSoft** [comment]
And here it is: https://padlock.io/news/v2.1-released/
