### ISSUE TITLE
Provide a way to close the detailed record view

### ISSUE THREAD

**Issue by dickolsson** [MaKleSoft/padlock#118]
It would be nice to have a way to close the "detailed view" (the right side) of a record. Because once I opened a record there's no way for me to quickly/easily hide all the passwords that are on my screen.

What I usually end up doing is clicking on the settings icon to hide the view. But this experience is a bit clunky.

Either some kind of "X" to close the detailed view. Or maybe a "<" to go back/close the detailed view, as the mobile UI works.

<img width="511" alt="screen shot 2017-09-25 at 07 05 36" src="https://user-images.githubusercontent.com/112085/30793159-4a1cc2fe-a1c0-11e7-90fb-5e1a84e2c64c.png">

**Comment by MaKleSoft** [comment]
> Either some kind of "X" to close the detailed view. Or maybe a "<" to go back/close the detailed view, as the mobile UI works.

@dickolsson I thought about a way to do this but couldn't think of one that didn't look awkward or confusing. A back arrow doesn't really make sense in this case since we're not going back to anything and an "X" would look strange next to the "X" of the filter input. Finally, putting an "X" on the right side next to the trash icon could be confusing because both icons could be interpreted as "delete record".

Now, you can actually close a record by deselecting it, which can be done several ways.

1. Click the corresponding item in the list view
2. Select the corresponding item using the up and down arrow buttons, then hit `Enter` (after you open a record, the corresponding list item will be selected by default, so just hitting `Enter` will be sufficient most of the time)
3. Hit `Escape`. This also works for closing the settings and cloud view

I think once users are familiar with the above methods, a close button becomes redundant. But I do admit that they are currently not easy to discover. I'll try to address this issue in the next release.

**Comment by MaKleSoft** [comment]
With field values being masked by default (https://github.com/MaKleSoft/padlock/pull/133), I think this is a non-issue now, so I'm closing this.
