### ISSUE TITLE
Support Touch ID on ios

### ISSUE THREAD

**Issue by pwasiewicz** [MaKleSoft/padlock#136]
It would be nice to integrate Touch ID authentication for IOS devices f.e. with the following plugin: https://github.com/EddyVerbruggen/cordova-plugin-touch-id

I'd be happy to implement this feature but..  unfortunately, I do not own MacOS device to test & deploy app to my iOS device.

**Comment by MaKleSoft** [comment]
Duplicate: https://github.com/MaKleSoft/padlock/issues/21

So far my stance on this has been to avoid third-party authentication layers like Touch ID. Apart form the security implications mentioned in the other issue, there is also the problem of users forgetting their master passwords because they never need to type them.

Regardless of all the other issues I have with this, there is now also the fact that with the announcement of the of the iPhone X and face id, it's not even clear if TouchID is gonna be around for much longer.

Anyway, closing this issue now, you can weigh in on the discussion in https://github.com/MaKleSoft/padlock/issues/21 if you want.
