### ISSUE TITLE
Add fingerprint unlock on Android

### ISSUE THREAD

**Issue by 21xhipster** [MaKleSoft/padlock#155]
Actually, the most necessary feature that stops me from Padlock usage instead of Lastpass

**Comment by pwasiewicz** [comment]
I think it is related to #21 (despite #21 is about TouchID on ios) but the point is the same.

**Comment by MaKleSoft** [comment]
Fingerprint unlock is one of those convenience features that lots of users ask for without realising the potential security risks and UX implications (lots of users forget their master password because they never need to type it). We're looking into other methods of authentication but it's a hard problem to solve. Closing this for now as a duplicate of #21.
