### ISSUE TITLE
[Q] Why limit 4 imputs view

### ISSUE THREAD

**Issue by beaucoralk** [MaKleSoft/padlock#164]
Hello,

Nice apps, just one question, why did you limit the list of visible inputs to 4 here : https://github.com/MaKleSoft/padlock/commit/8489c6ea2818a3c6e0d092311fa0fa10a9d88195#diff-78e80cd7a51f08feada0f8c868efb90fR184 ?

I prefere use multiple input, one for each account of the same "application", example for all my mysql accounts, I prefere create only one record with multiple input (one for each account), I think that your interface is better with this usages.

**Comment by MaKleSoft** [comment]
Good question, @beaucoralk! The list view is intended to provide an overview of all your records rather than displaying the entire information. While you personally would like to see all fields displayed in the list view, some users have complained that having records with many fields would clutter the list and lead to some UX issues. I think it's worth pointing out that while it's possible to have a large number of fields in any record, that is not necessarily how the app is intended to be used. In your use case specifically, I would recommend splitting up your "mysql" record into multiple records, maybe with a common tag. This improves discoverability and makes the data easier to manage. Here is an example of how this could look:

![image](https://user-images.githubusercontent.com/1270940/37771719-343d93f4-2db7-11e8-8bb5-e1a04c67c2aa.png)

Of course you're free to use the app however you'd like, and we designed it to leave you as much freedom in that as possible, but it's important to find a balance between providing flexibility and optimising for the most common use case. In this case we decided that displaying the first 4 fields in the list view is enough for the majority of users.

I'm closing this now, but I'd like to emphasise that your feedback has been noted and will be considered for future releases. For example, we may add an option in the settings to customise the maximum amount of fields displayed. In any case, thank you for taking the time to submit your feedback! Please keep it coming!
