### ISSUE TITLE
iOS - unlock using fingerprint insted of password.

### ISSUE THREAD

**Issue by peldax** [MaKleSoft/padlock#177]
Hello,
the title says it all. I would like to unlock my iOS application using fingerprint.

The downside of this is possible insecurity of finger scanners. I don't know much about security and reliability of those finger scanners so I believe it should be opt-in, but even if they weren't 100% reliable, the security disadvantage of your approach is that majority of users are lazy (including me) and when they have to type master password every time they use the application (its surely multiple times per hour), its gonna convert to situation where the choose easier and shorter passwords.

On computer its OK for me to type my 15+ character long master password, but on mobile, its really slow and painful - especially with special characters, switching keyboards and such - so it might be good idea to use their built-in security feature.

Thanks for your time, your app looks great. If I were better at JS, I would definitely help out.

**Comment by MaKleSoft** [comment]
@peldax You make some good points, specifically about users using shorter passwords out of convenience. We've been on the fence on biometric authentication due to security concerns but I believe the technology is now at the point were it is worth revisiting the idea. Closing this as duplicate of https://github.com/MaKleSoft/padlock/issues/21
