### ISSUE TITLE
_pause doesn't _lock?

### ISSUE THREAD

**Issue by dploeger** [MaKleSoft/padlock#19]
I'm just looking through the source code wether the app supports auto-locking (the vault is locked when the app is sent to the background).

If I read this right, the [_pause-method](https://github.com/MaKleSoft/padlock/blob/master/src/components/app/app.js#L135) is called when this event happens. But the _pause-method doesn't call the _lock-method. It seems to hide the view, the user currently is in (which could result in showing the lock-view I guess), but it i.e. doesn't delete the remote source password, as _lock does. Or am I missing something here?

**Comment by MaKleSoft** [comment]
@dploeger That is right. Pausing the app does not clear the data but really only shows the lock screen to prevent somebody else who picks up the device to access the data directly. Can you think of a reason why this might be a security risk? (I can think of one but I'd like to hear your reasoning). The problem with locking down the app on pause is that there is only a limited time after the pause event is triggered and before the app is suspended. The main goal of the current implementation was to hide any displayed data before the screenshot is taken that is used in the app switcher. As it turns out this is not working properly anymore in iOS 9 so we'll have to do something about this in any case.

I am actually leaning towards disabling the auto-lock feature completely and having the user rely on the native screen lock instead since reentering the password every time you switch apps can become very cumbersome...

**Comment by dploeger** [comment]
Let's take a step back and I'll tell you, what I would want from padlock:

1. Auto lock after some seconds - because people tend to not lock their apps before switching them (at least I don't ;-) ) - so you'll have to reenter your vault's password. This would mitigate the vector when you switch to the device's home view and leave your device lying around and other people switch into the vault
2. Screenlock directly when switching the app, so others cannot glance at the passwords when switching, but you don't have to enter the vault's password when going back to the app 

(I guess number two is actually what you've accomplished in _pause, right? Sorry)

So, no. I wouldn't disable the auto-lock feature. It only has to auto-lock after some seconds or minutes (I'd suggest 1 minute).

**Comment by MaKleSoft** [comment]
Actually, the actions performed in the `_pause` method currently achieve `1.` but not `2.`. Even though the memory is not cleared of the data when pausing, the app still requires the user to reenter the password before proceeding. However, it seems that in iOS 9 the screen switch is not performed fast enough to hide sensitive data inside the app switcher.

As for your first point: Yes, locking the app automatically after a certain time span is certainly a useful feature, but it becomes somewhat redundant if the native screen lock is enabled. If the user leaves their device lying around, the screen lock will prevent other people from meddling with the device. The question here is not if its a useful feature to implement, but rather if it is useful enough to justify the added complexity. This is a question I ask myself about every new (and even existing) features before implementing them. Let me think about this for a bit.

**Comment by MaKleSoft** [comment]
@dploeger I think you'll find the new auto locking behaviour will be more like what you're asking for. Look for it in the upcoming release! (Probably v1.0.0)
