### ISSUE TITLE
Two-Factor Authentication?

### ISSUE THREAD

**Issue by cclafferty** [MaKleSoft/padlock#24]
I'd like to start a discussion regarding a feature for [Two-Factor Authentication](https://en.wikipedia.org/wiki/Two-factor_authentication). I think the subject of it's security is arguable both for and against but I hope this thread reveals how we could implement it or at least a good argument for why we shouldn't.

Let me start with some points:
* 2FA usually consists of Device, SMS, Email, and Phone methods. I believe if we are to implement any of it we should only concern ourselves with Device (Google Authenticator) for now. The reason being that all other methods require external server support.
* I personally use [DUO](https://itunes.apple.com/gb/app/duo-mobile/id422663827?mt=8) (similar to Google Authenticator) and I know a lot of others use these too. I would suggest starting with support for [Time-based-one-time-passwords](https://en.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm) (TOTP).
* 2FA should be an option but be disabled by default when starting to use the app for the first time. Enabling 2FA and setting it up should be done via the Settings screen. This is my personal preference anyway.
* We should consider if the 2FA tokens simply allow access to the application or if they contribute to part of the encryption key. I'm inclined to say just restrict access to the application for now as I don't feel messing with key generation is a good idea just yet.
* Losing access to your 2FA device would be devastating unless we provide the user backup codes. These backup codes should be provided after setup has been completed. Unlike other online service providers we can't rely on an email fallback if they lose their device as we don't want to rely on external services.
* Finally is 2FA worth it for locally run software? Jailbreaking your phone or gaining access to your computer may allow you to bypass this check entirely. I know Chrome plugins are easily manipulated via Chrome Developer Tools, it's just JavaScript after all but iPhone and Android apps will need to be jailbroken before anything can be changed. So does employing 2FA give us more security? Does defence in depth apply here?

Here are some working solutions to 2FA:
* [Speakeasy.js](https://github.com/markbao/speakeasy/blob/master/lib/speakeasy.js) a 2FA library for Node.js is small working implementation of a TOTP algorithm. 
* [NOTP](https://github.com/guyht/notp/blob/master/index.js) another Node.js TOTP module implements an even smaller implementation of TOTP.
* Finally here is an article from Auth0 describing how to add 2FA to you're Node.js app. (not perfect for our use case but describes a lot) [From theory to practice: Adding Two-Factor Authentication to Node.js](https://auth0.com/blog/2015/08/20/from-theory-to-practice-adding-two-factor-to-node-dot-js/)

I personally believe that 2FA is a fairly simple to implement and that as it doesn't _need_ to affect the encryption scheme we should have little risk in adding it. It's lightweight security to restrict access to the application, but is it too lightweight that we risk making the app more complicated for little benefit?

Your thoughts?

**Comment by MaKleSoft** [comment]
Thanks for bringing this up, @cclafferty. I think this definitely makes sense to talk about, especially since more and more password managers start supporting this. My opinion is that 2FA in the sense that you are describing does not make any sense for Padlock. Let me explain why:

The entire premise of 2FA is that in order to access the functionality or data in question, a person needs two independent things. In most cases, this is a secret password and a mobile device or access to an email account. I would argue that in a way, this is already given in the case of Padlock.

By default, all data is stored locally on the device. In order to get access to the data, an attacker has to be both in possession of the device and know the master password. Even if the attacker manages to get hold of the raw data, they will not be able to access it unless they either know or can guess the master password. On the other hand, even if the attacker knows the master password, that information is useless unless they can get their hands on the data.

Of course this situation changes once you start synchronising your data with Padlock Cloud because now the data is available through a public api, which means an attacker does not need direct access to a physical hard drive any more. Padlock Cloud deals with this by issuing a device-specific authentication token that needs to be activated using a corresponding activation token. The authentication token is sent to the client directly while the activation token is sent to the users email address in form of an activation link. Note that the data stored in the cloud is still encrypted using the users master password so even if an attacker manages to get control over a users email account or even steal the entire database, knowledge of the master password is still required to access the information.

Let me also mention that incorporating a third-party 2FA service into the encryption scheme would a **very** bad idea for an entirely different set of reasons that I don't have time to get into right now.

I hope I was able to clearly explain my point. If there is anything that was not entirely clear of if you see any fault in my reasoning, please do let me know!

**Comment by cclafferty** [comment]
Thanks for taking the time to respond to this @MaKleSoft. It's helped shed light on some of the hesitations I had on implementing 2FA on a locally run software. Although for the record I wasn't ever suggesting we put **third-party** 2FA services inside the encryption scheme. I was merely considering a solution whereby a portion of the key could be obtained by the 2FA proof, which in hindsight I don't think could work - as it's a proof. 

I found it interesting that apps such as Dashlane implement 2FA. I experimented by trying to use Dashlane without any internet connection and was surprised to find I couldn't access my data, data which exists on the device locally. This explains why and how they use 2FA although worries me that such restrictions exist when no internet access is available. There is a chance that if my account didn't have 2FA enabled then it would allow access however I have yet to test this. If this is the only way 2FA can be implemented in an app then I must admit **I'm no longer interested in such a feature**. Their implementation relies too much on external servers. 

Thanks also for taking the time to explain the synchronisation mechanism with the exchange of access tokens and authentication tokens. This is an area I'm very interested in. I love that you've provided both client and server as open source solutions. Thanks again

**Comment by dickolsson** [comment]
@MaKleSoft Here's my thoughts on this;

I agree that Padlock does a tremendous job at keeping the data safe both when used locally or with Padlock Cloud. The per-device token is implemented in a great way!

However, when using a password manager for ALL passwords, private keys, recovery seeds etc. it now becomes a single-point-of focus for a **targeted attack**.
A targeted attack will in most scenarios consist of (1) a side-channel attack (physical or digital) to steal the master password and (2) some kind of attack on the physical device itself, either temporarily stealing it, or otherwise compromising it.

Working with the assumption that the above scenarios are successfully executed by an attacker, then my Padlock application, it's data all all my secrets will be compromised. Although this is an extreme scenario, it is in fact possible to protect against!

Now, traditional 2FA implemented with OTP on the device itself (e.g. my phone) will not give any protection at all (since the attackers has the device). However, 2FA implemented with U2F/FIDO on a **separate** physical device such as a YubiKey[1] or TREZOR[2] will protect me even when an attacker is successful with the aforementioned two scenarios.

Considering that Padlock is storing my most critical, and most valuable, keys as a single-point-of potential weakness I want to know that I'm protected even if my master password and my hardware is compromised. This is possible with U2F/FIDO on a separate device.

[1]: https://www.yubico.com/products/yubikey-hardware/
[2]: https://blog.trezor.io/secure-two-factor-authentication-with-trezor-u2f-e940fd5a60af

**Comment by MaKleSoft** [comment]
The fundamental problem here is that once an attacker has physical access to your device they will also have access to your raw, encrypted data (unless it is protected with an additional layer of protection as it is, for example, in recent iOS versions). This means that any effort to access your plaintext data basically comes down to either breaking the encryption or guessing your master password (which the encryption key is derived from). Any form of 2FA, even one involving an external device, would have to be integrated directly in the encryption scheme in order to add any additional security. While this is theoretically possible, it would also significantly increase complexity and thereby introduce new possible points of failure and additional attack surface.

One major part of Padlocks philosophy is **Security Through Simplicity**. I worry less about the theoretical limitations of a protection scheme and more about **getting it right**. Implementing crypto is **hard**, and the danger of introducing fatal vulnerabilities by implementing over-engineered crypto is significantly higher than having "too little security".

Don't get me wrong, I absolutely understand your concern and an additional, hardware-based layer of security is in principal not a bad idea, but right now I don't think it the savest path is to stick with the current, battle tested and audited encryption scheme.
