### ISSUE TITLE
Pull to synchronize

### ISSUE THREAD

**Issue by eorroe** [MaKleSoft/padlock#45]
You know how in most apps we have "Pull To Refresh" can we have a "Pull to Sync"?

**Comment by MaKleSoft** [comment]
@eorroe I've been thinking about this ever since the sync feature was added. Unfortunately, it's not easy doing this well in a web-based app. Furthermore, this would only really make since on touch-enabled devices so I'm not sure if it's really worth adding this. In general, the same considerations apply here that I outlined in https://github.com/MaKleSoft/padlock/issues/48.

**Comment by eorroe** [comment]
Actually I noticed that PadLock autosyncs so I don't really think there's a need
