### ISSUE TITLE
UX Features

### ISSUE THREAD

**Issue by eorroe** [MaKleSoft/padlock#48]
I love the ux on this app, but there could still be some improvements like the no animation issue #35 but some other stuff too.

I only have one idea right now so that's why I named this issue **UX Features** so users can add to it:

Idea: Holding a record field, should popup an easy copy feature, where once I hold a list of field names pops up and as I swipe up and down on the fields, it selects those and when I release it copies it. That would make it easy to copy what I want, while easily seeing my other records. Instead of having to:
1. Tap record
2. Tap field
3. Copy

Now idk how hard this would be to implement but hopefully you understood what I meant. I'll see if I can find some type of GIF example if you don't understand.

**Comment by MaKleSoft** [comment]
Thanks, @eorroe that sounds like a great idea! Unfortunately, this is somewhat in conflict with Padlocks philosophy of being as simple and minimalistic as possible. Don't get me wrong, I really like your idea but I'm not 100% sure if this feature would be useful enough to justify the added complexity, both code and ux wise. Consider these questions:

- Really how much easier/faster is hold-move-release vs tap-tap-tap?
- Is the cognitive overhead more or less?
- How discoverable/intuitive is hold-move-release vs tap-tap-tap? Most users explore an app by tapping, few people actually try to tap-and-hold things.

I really appreciate these kinds of suggestions a lot, and rejecting them is never easy, but [feature creep](https://en.wikipedia.org/wiki/Feature_creep) is a real thing and in order to stay true to Padlocks philosophy we'll end up rejecting a lot more feature requests.

**Comment by eorroe** [comment]
Interesting I didn't know that's what it was called (feature creep).

> Really how much easier/faster is hold-move-release vs tap-tap-tap?

Depending on how you understood my idea, or how I explained and imagined it in my head. It kind of reduces a lot of friction if you're signing in to multiple things at a time and have lots of records.

Again I'll see if tomorrow I can find a GIF or produce an example

**Comment by MaKleSoft** [comment]
I'm guessing you're envisioning something like the 3d touch [homescreen quick actions](https://developer.apple.com/ios/human-interface-guidelines/extensions/home-screen-actions/) on iOS?

**Comment by eorroe** [comment]
Yes and it would popup showing the fields of that record, and then whichever field you release your finger on it'll copy. Because majority of the time the main functionality used in the app will be copying

**Comment by MaKleSoft** [comment]
I definitely see what you mean. Let me think about it!

**Comment by eorroe** [comment]
Thought of an easier way no need for the drag feature, when a record is held, you could just show the fields, just like normal, except instead of showing options after tapping a field, it should automatically copy, and go back to showing the other records. Again this only happens after being held, not when tapped normally

**Comment by MaKleSoft** [comment]
@eorroe Closing this for now, but I put this in the backlog along with other potential ux tweaks. Thanks again for your suggestions!
