### ISSUE TITLE
Chrome app does not connect to a custom server

### ISSUE THREAD

**Issue by ReclusiveGeek** [MaKleSoft/padlock#58]
The Andriod app works fine and synchronises with the custom server. But the Chrome app give the message "Failed to connect to Padlock Cloud. Please check your internet and try again!".

The browser works and I can connect to the login screen. I am using LInux and have tried it on several distros and versions but the Chrome app does not work. It does work with your own cloud.

**Comment by MaKleSoft** [comment]
What versions of Padlock / Padlock Cloud are you running? Without any additional information, I'm guessing that your requests are blocked due to the same origin-policy within chrome (the chrome app does not allow requests to any domains other than cloud.padlock.io, which is specified as a exception). You can easily fix this by enabling Cross-Origin Resource Sharing on your server instance. Simply use the `--cors` flag: `padlock-cloud runserver --cors`. Let me know if that works for you!

**Comment by ReclusiveGeek** [comment]
The client in version 1.1.0 and the server is version 1.0.0. I have added cors: to the server section of the config file and restarted the server, and did not get any errors. The client is still giving the error message.

**Comment by MaKleSoft** [comment]
Have you checked your server logs? If you tell me the url to your padlock cloud instance I'll be happy to see if I can reproduce the problem.

**Comment by ReclusiveGeek** [comment]
I have got it to work. The config file needed "cors: true" in the server section. Might be an idea to update the config section of the README.md to reflect this.

Thanks a great project and might be a good idea to add a donate button to the website for those of us who run our own cloud servers and are happy to donate to open source projects.

Many thanks

**Comment by MaKleSoft** [comment]
Glad to hear it! I added a note about this in the Padlock Cloud readme: https://github.com/MaKleSoft/padlock-cloud#chrome-app-fails-to-connect-to-custom-server
