### ISSUE TITLE
Padlock doesn't use same storage across different browsers.

### ISSUE THREAD

**Issue by bkjohnson** [MaKleSoft/padlock#61]
I opened Padlock on a local server and added a few entries.  I then decided to open Padlock from a different browser, but rather than showing me the entries I had just added in the other browser it asked me to create a master password again.  I didn't complete this step, but I think that Padlock should have realized that I already created a master password and a few entries.

If I use 3 different browsers and I have to open Padlock in each of them and add an entry for every account I have, then it loses a lot of utility as a password manager.

**Comment by MaKleSoft** [comment]
@bkjohnson This the expected behaviour, since as of now Padlock uses the browsers localStorage api to store data. (See https://github.com/MaKleSoft/padlock/issues/55). **Note that serving the app via a local server and loading it through the browser is only recommended for development purposes!** For actual 'production' use, please make sure to use one of the 'native' builds. Official builds are available [here](https://github.com/MaKleSoft/padlock/releases). An official build for Linux will be available soon. For now you can build the app yourself:

```sh
git fetch && git checkout v1.2
npm install
gulp build --linux
```
