### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by netvl** [MaKleSoft/padlock#66]
It seems that there is no addon for Firefox. Sadly, this makes padlock unusable for me, and probably not only for me. Are there any plans to create one?

**Comment by MaKleSoft** [comment]
Can you explain what exactly you would expect from a Firefox addon and why it is essential for you? We've been shying away from implementing browser addons since they come with a lot of security challenges and generally introduce a level of complexity that we're trying to avoid. Personally I favour the copy/paste approach since it's 'good enough' while being much more transparent and generally more secure.

**Comment by eriklogtenberg** [comment]
I think a browser plugin would have convenience features like:
- automatically fill in stored user/password fields (just like most browser do out of the box, but then stored in a good password manager)
- automatically learn new user/passwords when user makes a new account somewhere
- and/or instead of just learning a new password, provide option to create a strong random password and automatically enter it

While I agree that copy/paste is "good enough" in that it _works_, these convenience features surely add a lot to the user experience, I think.

**Comment by MaKleSoft** [comment]
@eriklogtenberg All of the features you are describing require a level of intrusiveness that we've actively been trying to avoid. Convenience is nice, but these kinds of features come with a heavy price. Quite frankly, I don't have enough confidence that we can implement these features securely enough without sacrificing most if not all of the usefulness. Auto-fill related features have been a major attack surface of password managers in the past and it seems even the most popular ones haven't really figured it out yet. Here are just a few examples:

https://labs.detectify.com/2016/07/27/how-i-made-lastpass-give-me-all-your-passwords/
https://bugs.chromium.org/p/project-zero/issues/detail?id=888
https://bugs.chromium.org/p/project-zero/issues/detail?id=884
https://bugs.chromium.org/p/project-zero/issues/detail?id=890

So for now this is still a no-go, sorry.
