### ISSUE TITLE
Ask for master password when importing encrypted data

### ISSUE THREAD

**Issue by eorroe** [MaKleSoft/padlock#79]
I'm not completely sure on how this works, reporting this from what I can recall.

When importing my encrypted data, into PadLock I don't remember it asking me for my master password.

Doesn't that mean if someone gets access to my data and downloads PadLock, imports my data, they can read my data?

**Comment by MaKleSoft** [comment]
> When importing my encrypted data, into PadLock I don't remember it asking me for my master password.

It does, though: https://github.com/MaKleSoft/padlock/blob/master/src/components/import-view/import-view.js#L74

Remember that it is impossible by design to decrypt/encrypt your data without the master password. The reason why you don't need to provide the master password every time you save changes or synchronise with Padlock Cloud is that Padlock remembers your password **only while you're logged in**. In case of an import, Padlock assumes that the password is different from your current one, so it asks every time.

> Doesn't that mean if someone gets access to my data and downloads PadLock, imports my data, they can read my data?

To summarise: no :)

**Comment by eorroe** [comment]
Cool, I wasn't sure, again don't remember it asking so that's why I asked. I could of tested, but was easier to open an issue 😉
