### ISSUE TITLE
Kanban view

### ISSUE THREAD

**Issue by eorroe** [MaKleSoft/padlock#83]
I think a simple kanban view by labels would be nice for PadLock. Where each record is alphabetically sorted. Each record is duplicated across each label.

**Comment by MaKleSoft** [comment]
@eorroe Not sure what you mean by 'labels' or what the end result would look like. Can you elaborate?

**Comment by eorroe** [comment]
Sorry about that I mean "category" instead. I have like 10 categories and would love a kanban view of each record in a column by category where I can easily scroll each column like Kanban View

Right now it looks like a contacts list. I'm aware I can just type out the category and have it show the results like so.

But it'd be interesting to experiment with and see which one people like best?

**Comment by MaKleSoft** [comment]
> But it'd be interesting to experiment with and see which one people like best?
I agree that trying new things is important to continuously improve the user experience. However, it's easy to get carried away with things like this and there are other things that have higher priority right now. I like the idea but quite frankly implementing something like this would be a lot of work and since we just overhauled the user experience for v2.0 I don't think it's going to happen any time soon. Thanks for the idea though! I really appreciate the input.
